// Generated by build/write_buildflag_header.py
// From "//base/win:base_win_features"

#ifndef BASE_WIN_BASE_FEATURES_H_
#define BASE_WIN_BASE_FEATURES_H_

#include "build/buildflag.h"

#define BUILDFLAG_INTERNAL_SINGLE_MODULE_MODE_HANDLE_VERIFIER() (0)

#endif  // BASE_WIN_BASE_FEATURES_H_
